# Generated by Django 5.0.6 on 2024-06-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="end_date_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_date_time",
            field=models.DateTimeField(),
        ),
    ]
