# Generated by Django 4.0 on 2024-06-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_event_end_date_event_end_time_event_start_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="max_price",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="event",
            name="min_price",
            field=models.FloatField(default=0),
        ),
    ]
